[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2021"
resolver = "2"
# if we auto build - it fails the Flutter packages that use this one
build = false

[lib]
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "codegen"
path = "build.rs"
required-features = ["build_deps"]

[dependencies]
flutter_rust_bridge = "=1.82.6"
flutter_rust_bridge_codegen = { version = "=1.82.6", optional = true }
anyhow = "1.0.*"
serde = "1.0.*"
serde_json = "1.0.*"
parking_lot = "0.12.*"
lazy_static = "1.*"
deserr = "0.5.0"
either = "1.8.1"
regex = "1.7.3"
thiserror = "1.0.40"
obkv = "0.2.0"

milli_v1 = { git = "https://github.com/meilisearch/meilisearch", package = "milli", tag = "v1.2.0" }
meilisearch_types = { git = "https://github.com/meilisearch/meilisearch", package = "meilisearch-types", tag = "v1.2.0" }
permissive_json_pointer = { git = "https://github.com/meilisearch/meilisearch", package = "permissive-json-pointer", tag = "v1.2.0" }
meilisearch_auth= { git = "https://github.com/meilisearch/meilisearch", package = "meilisearch-auth", tag = "v1.2.0" }
#milli_v1 = { git = "https://github.com/meilisearch/meilisearch", package = "milli", tag = "v1.3.0" }
#milli_v1 = { git = "https://github.com/lming/meilisearch", package = "milli", branch = "v1.5.1_mimalloc" }
#meilisearch = { git = "https://github.com/lming/meilisearch", package = "meilisearch", branch = "v1.5.1_mimalloc" }
#index_scheduler = { git = "https://github.com/lming/meilisearch", package = "index-scheduler", branch = "v1.5.1_mimalloc" }
#meilisearch_types = { git = "https://github.com/lming/meilisearch", package = "meilisearch-types", branch = "v1.5.1_mimalloc" }
#meilisearch = { git = "https://github.com/meilisearch/meilisearch", package = "meilisearch", tag = "v1.2.0" }
#milli_v1 = { git = "https://github.com/lming/meilisearch", package = "milli", branch = "v1.3.1_mimalloc" }
#meilisearch = { git = "https://github.com/lming/meilisearch", package = "meilisearch", branch = "v1.3.1_mimalloc" }

[patch.crates-io]
charabia = { version = "0.8.5", default-features = false }
# libmimalloc-sys = { version = "0.1.33" }
mimalloc = { version = "0.1.29", default-features = false }

[features]
default = ["milli_v1/all-tokenizations",]
# POSIX semaphores are needed for Apple's App Sandbox.
# Default LMDB uses SysV semaphores but App Sandbox disallows them.
# See https://github.com/GregoryConrad/mimir/issues/98
posix-sem = ["milli_v1/lmdb-posix-sem",]
build_deps = ["flutter_rust_bridge_codegen"]
