[package]
name = "embedded_milli"
version = "0.0.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
flutter_rust_bridge_codegen = "=1.82.6"

[dependencies]
flutter_rust_bridge = "=1.82.6"
anyhow = "1.0.*"
serde = "1.0.*"
serde_json = "1.0.*"
parking_lot = "0.12.*"
lazy_static = "1.*"
#milli_v1 = { git = "https://github.com/meilisearch/meilisearch", package = "milli", tag = "v1.3.0" }
milli_v1 = { git = "https://github.com/lming/meilisearch", package = "milli", branch = "v1.5.1_snippets" }
meilisearch = { git = "https://github.com/lming/meilisearch", package = "meilisearch", branch = "v1.5.1_snippets" }
index_scheduler = { git = "https://github.com/lming/meilisearch", package = "index-scheduler", branch = "v1.5.1_snippets" }
meilisearch_types = { git = "https://github.com/lming/meilisearch", package = "meilisearch-types", branch = "v1.5.1_snippets" }

[patch.crates-io]
charabia = { version = "0.8.5" }

[features]
default = ["milli_v1/all-tokenizations",]
# POSIX semaphores are needed for Apple's App Sandbox.
# Default LMDB uses SysV semaphores but App Sandbox disallows them.
# See https://github.com/GregoryConrad/mimir/issues/98
posix-sem = ["milli_v1/lmdb-posix-sem",]
